# Generated by Django 4.0.6 on 2022-07-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funddocument',
            name='file_en',
            field=models.FileField(null=True, upload_to='fond_documents/'),
        ),
        migrations.AddField(
            model_name='funddocument',
            name='file_pl',
            field=models.FileField(null=True, upload_to='fond_documents/'),
        ),
        migrations.AddField(
            model_name='funddocument',
            name='file_uk',
            field=models.FileField(null=True, upload_to='fond_documents/'),
        ),
        migrations.AddField(
            model_name='funddocument',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='funddocument',
            name='name_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='funddocument',
            name='name_uk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
