# Generated by Django 4.0.6 on 2022-07-20 11:59

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSystemCurrency',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='address',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='bic',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='corespondent_banks',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='fund_name',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='iban',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='payment_purpose',
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='currency_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PaymentSystem',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(choices=[('FONDY', 'Fondy')], default='FONDY', max_length=255, primary_key=True, serialize=False)),
                ('is_visible', models.BooleanField(default=True, help_text='Is visible on website')),
                ('currencies', models.ManyToManyField(to='payments.paymentsystemcurrency')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentDetailsField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(max_length=255)),
                ('payment_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='payments.paymentdetails')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
