# Generated by Django 4.0.6 on 2022-07-19 15:51

import datetime
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_uk', models.CharField(max_length=255, null=True, unique=True)),
                ('name_en', models.CharField(max_length=255, null=True, unique=True)),
                ('name_pl', models.CharField(max_length=255, null=True, unique=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('preview_photo', models.ImageField(help_text='Photo that displayed in news list', upload_to='previews/%Y-%m-%d/')),
                ('title', models.CharField(max_length=255)),
                ('title_uk', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_pl', models.CharField(max_length=255, null=True)),
                ('publication_date', models.DateField(default=datetime.date.today)),
                ('annotation', models.TextField()),
                ('annotation_uk', models.TextField(null=True)),
                ('annotation_en', models.TextField(null=True)),
                ('annotation_pl', models.TextField(null=True)),
                ('content', models.TextField()),
                ('content_uk', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
                ('content_pl', models.TextField(null=True)),
                ('tags', models.ManyToManyField(related_name='news', to='news.newstag')),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
