# Generated by Django 4.0.6 on 2022-07-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='annotation',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='annotation_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='annotation_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='annotation_uk',
            field=models.TextField(null=True),
        ),
    ]
