# Generated by Django 4.0.6 on 2022-07-19 15:08

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_annotation_news_annotation_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=200, null=True, populate_from=('title',), unique=True),
        ),
    ]
