# Generated by Django 4.0.6 on 2022-07-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newstag_slug_alter_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='main_photo',
            field=models.ImageField(help_text='Photo that displayed in top of news page', null=True, upload_to='main_photos/%Y-%m-%d/'),
        ),
    ]
