# Generated by Django 4.0.6 on 2022-09-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_news_main_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='annotation_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newstag',
            name='name_es',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
