# Generated by Django 4.0.6 on 2022-08-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_helpemailreceiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpemailreceiver',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
